name: Docker Image CI

on:
  push:
    tags:
      - '*'  # Trigger on any tag push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io # Replace with your registry if needed
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: app-attest-service:${{ github.ref | replace('refs/heads/', '') | replace('refs/tags/', '') }}   # Use the tag as the image tag
